repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        name: black
        files: ^sdk/.*/speechmatics/
        args: [--line-length=120, --target-version=py39]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        name: ruff
        files: ^sdk/.*/speechmatics/
        args:
          - --fix
          - --line-length=120
          - --exit-non-zero-on-fix

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        files: ^sdk/.*/speechmatics/.*/.*\.py$
        args:
          [--ignore-missing-imports, --warn-unused-configs, --show-error-codes]
        additional_dependencies:
          [websockets, aiohttp, structlog, types-aiofiles]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^sdk/.*/speechmatics/
        args: [-r, -f, json, -ll]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
        files: ^sdk/.*/speechmatics/
      - id: python-no-log-warn
        files: ^sdk/.*/speechmatics/
      - id: python-use-type-annotations
        files: ^sdk/.*/speechmatics/

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: make test-all
        language: system
        files: ^(sdk/.*/speechmatics/|tests/).*\.py$
        stages: [manual]
        pass_filenames: false
        always_run: false

default_stages: [pre-commit]
