name: Release RT SDK

on:
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update package version in speechmatics/rt/__init__.py
        run: sed -i 's/0.0.0/${{ github.event.release.tag_name }}/g' ./speechmatics/rt/__init__.py

      - name: Build dist
        working-directory: speechmatics/rt
        run: |
          make install-dev
          make test
          make lint
          make build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: release-dist
          path: speechmatics/rt/dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/speechmatics-rt/${{ github.event.release.tag_name }}

    steps:
      - name: Retrieve release dist
        uses: actions/download-artifact@v4
        with:
          name: release-dist
          path: speechmatics/rt/dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package-dir: speechmatics/rt/dist/
