name: Test and Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test-rt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test and build RT SDK
        run: |
          make install-dev
          make build-rt
          make lint-rt
          make test-rt

  test-batch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test and build Batch SDK
        run: |
          make install-dev
          make build-batch
          make lint-batch
          make test-batch
