name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-rt:
    name: Test RT SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install-dev
      - name: Lint RT SDK
        run: make lint-rt
      - name: Test RT SDK
        run: make test-rt
      - name: Build RT SDK
        run: make build-rt

  test-batch:
    name: Test Batch SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install-dev
      - name: Lint Batch SDK
        run: make lint-batch
      - name: Test Batch SDK
        run: make test-batch
      - name: Build Batch SDK
        run: make build-batch

  test-flow:
    name: Test Flow SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install-dev
      - name: Lint Flow SDK
        run: make lint-flow
      - name: Test Flow SDK
        run: make test-flow
      - name: Build Flow SDK
        run: make build-flow

  test-voice:
    name: Test Voice Agent SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install-dev
      - name: Lint Voice Agent SDK
        run: make lint-voice
      - name: Test Voice Agent SDK
        run: make test-voice
      - name: Build Voice Agent SDK
        run: make build-voice
